// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sharing.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFilePermission = `-- name: CreateFilePermission :one
INSERT INTO file_permissions (file_id, user_id, role, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (file_id, user_id)
DO UPDATE SET role = EXCLUDED.role
RETURNING id, file_id, user_id, role, granted_by, created_at
`

type CreateFilePermissionParams struct {
	FileID    pgtype.UUID    `json:"file_id"`
	UserID    pgtype.UUID    `json:"user_id"`
	Role      PermissionRole `json:"role"`
	GrantedBy pgtype.UUID    `json:"granted_by"`
}

func (q *Queries) CreateFilePermission(ctx context.Context, arg CreateFilePermissionParams) (FilePermission, error) {
	row := q.db.QueryRow(ctx, createFilePermission,
		arg.FileID,
		arg.UserID,
		arg.Role,
		arg.GrantedBy,
	)
	var i FilePermission
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Role,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (file_id, token, created_by, permission, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_id, token, created_by, permission, expires_at, is_active, created_at
`

type CreateShareLinkParams struct {
	FileID     pgtype.UUID        `json:"file_id"`
	Token      string             `json:"token"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	Permission NullPermissionRole `json:"permission"`
	ExpiresAt  pgtype.Timestamp   `json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.FileID,
		arg.Token,
		arg.CreatedBy,
		arg.Permission,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Token,
		&i.CreatedBy,
		&i.Permission,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateShareLink = `-- name: DeactivateShareLink :exec
UPDATE share_links SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateShareLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateShareLink, id)
	return err
}

const getFilePermissions = `-- name: GetFilePermissions :many
SELECT fp.id, fp.file_id, fp.user_id, fp.role, fp.granted_by, fp.created_at, u.email, u.name as user_name
FROM file_permissions fp
JOIN users u ON fp.user_id = u.id
WHERE fp.file_id = $1
`

type GetFilePermissionsRow struct {
	ID        pgtype.UUID      `json:"id"`
	FileID    pgtype.UUID      `json:"file_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      PermissionRole   `json:"role"`
	GrantedBy pgtype.UUID      `json:"granted_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Email     string           `json:"email"`
	UserName  string           `json:"user_name"`
}

func (q *Queries) GetFilePermissions(ctx context.Context, fileID pgtype.UUID) ([]GetFilePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getFilePermissions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFilePermissionsRow{}
	for rows.Next() {
		var i GetFilePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.Role,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, file_id, token, created_by, permission, expires_at, is_active, created_at FROM share_links WHERE token = $1 AND is_active = TRUE
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByToken, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Token,
		&i.CreatedBy,
		&i.Permission,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getShareLinksByFile = `-- name: GetShareLinksByFile :many
SELECT id, file_id, token, created_by, permission, expires_at, is_active, created_at FROM share_links WHERE file_id = $1 AND is_active = TRUE
`

func (q *Queries) GetShareLinksByFile(ctx context.Context, fileID pgtype.UUID) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, getShareLinksByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Token,
			&i.CreatedBy,
			&i.Permission,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedWithMeFiles = `-- name: GetSharedWithMeFiles :many
SELECT f.id, f.name, f.original_name, f.mime_type, f.size, f.storage_path, f.owner_id, f.parent_folder_id, f.status, f.is_starred, f.thumbnail_path, f.preview_available, f.version, f.current_version_id, f.created_at, f.updated_at, f.trashed_at, f.last_accessed_at, u.name as owner_name, fp.role
FROM files f
JOIN file_permissions fp ON f.id = fp.file_id
JOIN users u ON f.owner_id = u.id
WHERE fp.user_id = $1 AND f.status = 'active'
`

type GetSharedWithMeFilesRow struct {
	ID               pgtype.UUID      `json:"id"`
	Name             string           `json:"name"`
	OriginalName     string           `json:"original_name"`
	MimeType         string           `json:"mime_type"`
	Size             int64            `json:"size"`
	StoragePath      string           `json:"storage_path"`
	OwnerID          pgtype.UUID      `json:"owner_id"`
	ParentFolderID   pgtype.UUID      `json:"parent_folder_id"`
	Status           NullFileStatus   `json:"status"`
	IsStarred        pgtype.Bool      `json:"is_starred"`
	ThumbnailPath    pgtype.Text      `json:"thumbnail_path"`
	PreviewAvailable pgtype.Bool      `json:"preview_available"`
	Version          pgtype.Int4      `json:"version"`
	CurrentVersionID pgtype.UUID      `json:"current_version_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	TrashedAt        pgtype.Timestamp `json:"trashed_at"`
	LastAccessedAt   pgtype.Timestamp `json:"last_accessed_at"`
	OwnerName        string           `json:"owner_name"`
	Role             PermissionRole   `json:"role"`
}

func (q *Queries) GetSharedWithMeFiles(ctx context.Context, userID pgtype.UUID) ([]GetSharedWithMeFilesRow, error) {
	rows, err := q.db.Query(ctx, getSharedWithMeFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedWithMeFilesRow{}
	for rows.Next() {
		var i GetSharedWithMeFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.StoragePath,
			&i.OwnerID,
			&i.ParentFolderID,
			&i.Status,
			&i.IsStarred,
			&i.ThumbnailPath,
			&i.PreviewAvailable,
			&i.Version,
			&i.CurrentVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.LastAccessedAt,
			&i.OwnerName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionForFile = `-- name: GetUserPermissionForFile :one
SELECT id, file_id, user_id, role, granted_by, created_at FROM file_permissions
WHERE file_id = $1 AND user_id = $2
`

type GetUserPermissionForFileParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetUserPermissionForFile(ctx context.Context, arg GetUserPermissionForFileParams) (FilePermission, error) {
	row := q.db.QueryRow(ctx, getUserPermissionForFile, arg.FileID, arg.UserID)
	var i FilePermission
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Role,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokePermission = `-- name: RevokePermission :exec
DELETE FROM file_permissions
WHERE file_id = $1 AND user_id = $2
`

type RevokePermissionParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokePermission(ctx context.Context, arg RevokePermissionParams) error {
	_, err := q.db.Exec(ctx, revokePermission, arg.FileID, arg.UserID)
	return err
}
